travis:
  secure:
    BINSTAR_TOKEN: B/7PL4PcEJ4lEswpZ8GENzI8nPF8sFWqbIJwijdzYOgpZbuY7OD63hOqNipCNRTMF7PRXbFl2WiUJ4xhztTgCG/GBdm2KvRA4Pqne3WRkl7tndh8HAJ4Yijk3lp0htEnEPDI4qGzm7sGzmqucfD6xLrx2e/5UGwBaAY2OJwFkfQokJ+9FVHqXW6Gdh30I7swnmAGLYi0zEOFAayu12gDsMyCEX0jHto9p35kYetoT/8RNaMRmRLFmINULS66PYXSNeuD3+BhC9GK3PUfjSaW/wS9Nf6KlajUFzT0JDQ8ksVVYdcSlsbuUscsu16qfcAPkdKJdl9pzVJ7PoyrDfskon/pckSlBqHxy7/VLICR5aByAUcMgkZvSm1YNpJ5l6l0fAK+stH7hjafBv7MpyImaWGA08iMOD4nIDNkKWIdnbLNAkSVml9dst6YZyrWZMpBdlHoU+JixcIlG1eYTklw0i+LBBHan1CPCYNRGK6SGiLGVMRFTqgqbwTLAACrEjrZVh5GhqupS4Js1aahHRZxo2Uk4if5CV9RuI4W7jCo2twY9HK8vGpKZXAwoLdXeSEVr9MXbtzPxsOaQtrpzZmJb3ZSuyUZyWrjqHMVCDCwFczYrIoul92fRCibJayLijpWM+9R9FMWRo+zJBNvohExv+W/59h0ha5qnr36vYq2jn4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
